### ISSUE TITLE
Download button deprecation issue

### ISSUE THREAD

**Issue by keshmaster81** [pragmatic-streamlit/streamlit-file-browser#42]
I'm having issues with the download button. Currently I don't have a download button appearing even though I have its parameter set to true. Here's a code snippet:` st.header('File Browser')
    event = st_file_browser(
        "/home/pi/daqhats/examples/python/mcc128/static/csv_data",
        key='file_browser',
        use_static_file_server=True,
        show_choose_file=False,
        show_delete_file=False,
        show_download_file=True,  # Enable the download button
        show_new_folder=False,
        show_upload_file=False,
        use_cache = False,
        #static_file_server_path="http://localhost:8000/?choose=true"`

And heres a pic of my GUI;
![image](https://github.com/user-attachments/assets/40d2e87f-a82b-4120-8a65-a23c9ce2af54)

Anytime I try to click on a file, I get the following error message: /home/pi/newbursterproject/lib/python3.11/site-packages/streamlit_file_browser/__init__.py:118: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  mask = df.applymap(type) != bool

Another issue is that when I specify the static file server path, the GUI stops working and I see this instead: 
![image](https://github.com/user-attachments/assets/6da12cf3-6ef3-4997-b500-cad9ac22a49e)

**Comment by y805939188** [comment]
> show_download_file

Hi. Since it is difficult to simulate a real file server to download files with `Streamlit`, so the `streamlit-file-browser` provides two parameters: `artifacts_site` and `artifacts_download_site` for supporting downloads. This means that if you want to download a file, you need to provide two HTTP paths.  The `artifacts_site` parameter is used to locate your file, and the `artifacts_download_site` is used for downloading your file. In this repo, a simple download demo is provided.

This demo uses `Caddy` which is a open source proxy server to create a simple file download server (https://github.com/pragmatic-streamlit/streamlit-file-browser/blob/main/Caddyfile):
```
http://localhost:1024 {
    log {
        output stdout
        level DEBUG
    }
    header /download/artifacts/* {
        +Content-Disposition "attachment"
    }
    route /download/artifacts/* {
        uri strip_prefix /download/artifacts
        file_server {
            root ./example_artifacts/
            disable_canonical_uris
        }
    }  
    route /artifacts/* {
        uri strip_prefix /artifacts
        file_server {
            root ./example_artifacts/
            disable_canonical_uris
        }
    }
    reverse_proxy /* 0.0.0.0:8501
}
```
To run this demo, first install `Caddy` (https://github.com/caddyserver/caddy?tab=readme-ov-file#install), clone this repo, then run `caddy run --config Caddyfile`:
<img width="763" alt="image" src="https://github.com/user-attachments/assets/33f26ad0-dcc7-4bc4-b36d-b41548bbf5a7">

Next, set `artifacts_site` to "http://localhost:1024/artifacts/", and `artifacts_download_site` to "http://localhost:1024/download/artifacts/".
 You can refer to the following:
```python
    event = st_file_browser(
        os.path.join(current_path, "..", "example_artifacts"),
        file_ignores=("a.py", "a.txt", re.compile(".*.pdb")),
        key="A",
        show_download_file=True,
        artifacts_site="http://localhost:1024/artifacts/",
        artifacts_download_site="http://localhost:1024/download/artifacts/",
        use_cache=True,
        sort=sort,
    )
    st.write(event)
```
Then you can download file normally.

The above is just a simple demo, you can use your own file server to support downloads.
